[package]
name = "muzzman-lib-internals"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.dev]
panic = 'unwind'
[profile.release]
panic = 'unwind'
debug = false

[dependencies]
rand = "0.8.5"
http = "0.2.8"
signals-kman = {path = "../../signals", features = ["advanced"]}
# signals-kman = {version = "0.0.5", features = ["advanced"]}
get_ref = {path = "../../get_ref"}
url = "2.3.1"
libloading = "0.7.4"
