[package]
name = "muzzman-local-session"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
muzzman-lib = {path = ".."}
